

services:
  server:
    build: ./server
    container_name: codesync-server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/codesync
    depends_on:
      - mongo
    restart: always

  client:
    build: 
      context: ./client
      args:
        - VITE_PISTON_URL=/piston/api/v2/execute
    container_name: codesync-client
    ports:
      - "5173:80"
    depends_on:
      - server
      - piston
    restart: always

  piston:
    image: ghcr.io/engineer-man/piston:latest
    container_name: codesync-piston
    privileged: true
    ports:
      - "2000:2000"
    volumes:
      - piston-data:/piston
    tmpfs:
      - /tmp:exec,mode=777
    restart: always

  mongo:
    image: mongo:latest
    container_name: codesync-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

  mongo-express:
    image: mongo-express:latest
    container_name: codesync-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017/codesync
    depends_on:
      - mongo

volumes:
  mongo-data:
  piston-data:
